### ISSUE TITLE
DashboardPort option not functional

### ISSUE THREAD

**Issue by c-nv-s** [iyashjayesh/monigo#12]
https://github.com/iyashjayesh/monigo/blob/5092668133a6576b3b8065b64e5c9128d9bcf06e/example/main.go#L15

changing your dashboard port field has no effect on the resulting port served... it always uses the default 8080

**Comment by miguellords** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by c-nv-s** [comment]
also... please include a local copy of echarts so that everything is self contained and will work offline
https://cdn.jsdelivr.net/npm/echarts@5.4.2/dist/echarts.min.js

**Comment by iyashjayesh** [comment]
> https://github.com/iyashjayesh/monigo/blob/5092668133a6576b3b8065b64e5c9128d9bcf06e/example/main.go#L15
> 
> changing your dashboard port field has no effect on the resulting port served... it always uses the default 8080
@c-nv-s It's already resolved in #11. can you try fetching the latest code?

**Comment by iyashjayesh** [comment]
@c-nv-s, Let me know once you verify. Thank you.

**Comment by c-nv-s** [comment]
https://github.com/iyashjayesh/monigo/blob/5092668133a6576b3b8065b64e5c9128d9bcf06e/monigo.go#L71

should be ``if len(m.DashboardPort) == 0 {``

**Comment by c-nv-s** [comment]
ah sorry I thought you had it as a ``string`` but it is an ``int``.
I think it might need a bit more thought but yes it still is not working on version 1.0.1 for me so maybe I'm doing something wrong.
Don't have time to investigate at the moment so maybe tomorrow or maybe on the weekend.

**Comment by iyashjayesh** [comment]
No worries, I understand. I've looked into the issue and raised a PR that addresses both the dashboard port and the ECharts local copy. If possible, could you review it? #15 
If everything looks good, I'll merge it and create a minor release.

**Comment by c-nv-s** [comment]
your PR does work now thanks.

I think something to consider, not now, but maybe for the future would be to allow the developer to be able to pass in a chain of middleware functions ( something like ``DashboardMiddleware []http.handlerfunc()`` ) or at least a custom auth function to protect the Dashboard view.

**Comment by iyashjayesh** [comment]
Glad it's working! I'll consider it along with #15. Thanks for the suggestion!
